// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ClientConn is an autogenerated mock type for the ClientConn type
type ClientConn struct {
	mock.Mock
}

type ClientConn_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientConn) EXPECT() *ClientConn_Expecter {
	return &ClientConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *ClientConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ClientConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ClientConn_Expecter) Close() *ClientConn_Close_Call {
	return &ClientConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ClientConn_Close_Call) Run(run func()) *ClientConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientConn_Close_Call) Return(_a0 error) *ClientConn_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientConn_Close_Call) RunAndReturn(run func() error) *ClientConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Invoke provides a mock function with given fields: ctx, method, args, reply, opts
func (_m *ClientConn) Invoke(ctx context.Context, method string, args interface{}, reply interface{}, opts ...grpc.CallOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, method, args, reply)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, interface{}, ...grpc.CallOption) error); ok {
		r0 = rf(ctx, method, args, reply, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientConn_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type ClientConn_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - args interface{}
//   - reply interface{}
//   - opts ...grpc.CallOption
func (_e *ClientConn_Expecter) Invoke(ctx interface{}, method interface{}, args interface{}, reply interface{}, opts ...interface{}) *ClientConn_Invoke_Call {
	return &ClientConn_Invoke_Call{Call: _e.mock.On("Invoke",
		append([]interface{}{ctx, method, args, reply}, opts...)...)}
}

func (_c *ClientConn_Invoke_Call) Run(run func(ctx context.Context, method string, args interface{}, reply interface{}, opts ...grpc.CallOption)) *ClientConn_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *ClientConn_Invoke_Call) Return(_a0 error) *ClientConn_Invoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientConn_Invoke_Call) RunAndReturn(run func(context.Context, string, interface{}, interface{}, ...grpc.CallOption) error) *ClientConn_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewStream provides a mock function with given fields: ctx, desc, method, opts
func (_m *ClientConn) NewStream(ctx context.Context, desc *grpc.StreamDesc, method string, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, desc, method)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NewStream")
	}

	var r0 grpc.ClientStream
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.StreamDesc, string, ...grpc.CallOption) (grpc.ClientStream, error)); ok {
		return rf(ctx, desc, method, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.StreamDesc, string, ...grpc.CallOption) grpc.ClientStream); ok {
		r0 = rf(ctx, desc, method, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ClientStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *grpc.StreamDesc, string, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, desc, method, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientConn_NewStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewStream'
type ClientConn_NewStream_Call struct {
	*mock.Call
}

// NewStream is a helper method to define mock.On call
//   - ctx context.Context
//   - desc *grpc.StreamDesc
//   - method string
//   - opts ...grpc.CallOption
func (_e *ClientConn_Expecter) NewStream(ctx interface{}, desc interface{}, method interface{}, opts ...interface{}) *ClientConn_NewStream_Call {
	return &ClientConn_NewStream_Call{Call: _e.mock.On("NewStream",
		append([]interface{}{ctx, desc, method}, opts...)...)}
}

func (_c *ClientConn_NewStream_Call) Run(run func(ctx context.Context, desc *grpc.StreamDesc, method string, opts ...grpc.CallOption)) *ClientConn_NewStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*grpc.StreamDesc), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *ClientConn_NewStream_Call) Return(_a0 grpc.ClientStream, _a1 error) *ClientConn_NewStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientConn_NewStream_Call) RunAndReturn(run func(context.Context, *grpc.StreamDesc, string, ...grpc.CallOption) (grpc.ClientStream, error)) *ClientConn_NewStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientConn creates a new instance of ClientConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientConn {
	mock := &ClientConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
